-- AlterTable
ALTER TABLE `User` ADD COLUMN `role` VARCHAR(191) NULL DEFAULT 'USER';

-- AddForeignKey
ALTER TABLE `Post` ADD CONSTRAINT `Post_authorId_fkey` FOREIGN KEY (`authorId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
